name: Distribute Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
    - name: Run image
      uses: abatilo/actions-poetry@v2.1.6
        with:
          poetry-version: 1.2.0
    - name: Publish
        run: |
          poetry config http-basic.pypi ${{ secrets.PYPI_USERNAME }} ${{ secrets.PYPI_PASSWORD }}
          poetry publish --build
